- name: Install epel
  yum:
    name: epel-release
    state: latest

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Add Nginx config file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Reload Nginx

- name: Create web root directory
  file:
    path: /var/www/html
    state: directory
    owner: nginx
    group: nginx
    mode: "0755"

- name: Create index.html file
  copy:
    content: "Hello World!\n{{ inventory_hostname }}"
    dest: /var/www/html/index.html

- name: Restart nginx
  service:
    name: nginx
    state: restarted
